### ISSUE TITLE
Vue 3.2.31 + Vite 2.7.1 initVimMode cause CPU usage 100%

### ISSUE THREAD

**Issue by vikyd** [bazingaedward/monaco-editor-vue3#11]
Vue 3.2.31 + Vite 2.7.1 initVimMode cause CPU usage 100%

Online demo: https://stackblitz.com/edit/vitejs-vite-hkhm2v?file=src%2FApp.vue

try to input something in editor, will cause CPU 100%.

**Comment by doyong-lee** [comment]
I have the same problem.

When I call a function that changes scroll as shown below, the browser freezes.

>>> editor.revealLine(15);

**Comment by bazingaedward** [comment]
@vikyd got it，i will check it soon and reply to you

**Comment by vikyd** [comment]
got it.

We should not use Vue `ref` to declare `editor` variable, which will cause performence problem.

Just use `let editor = ` or `const editor = ` is fine. 

see: https://github.com/microsoft/monaco-editor/issues/3154#issuecomment-1161170756

**Comment by nanfb** [comment]
> 知道了。
> 
> 我们不应该使用Vue`ref`来声明`editor`变量，这会导致性能问题。
> 
> 只需使用`let editor = `或`const editor = `即可。
> 
> 参见：[microsoft/monaco-editor#3154 (评论)](https://github.com/microsoft/monaco-editor/issues/3154#issuecomment-1161170756)

是这样的。使用响应式赋值会导致页面卡死hh，作者可以在文档里说一下。
