### ISSUE TITLE
TypeScript errors

### ISSUE THREAD

**Issue by dannysmc95** [bazingaedward/monaco-editor-vue3#12]
Hi there, I keep seeing this issue:

![image](https://user-images.githubusercontent.com/5339861/200812174-1506c28e-696d-41aa-83f6-87c6f71df59c.png)

Current code is this:
![image](https://user-images.githubusercontent.com/5339861/200812229-02a34e26-e6bc-4044-ae3a-9f237300331b.png)

**Comment by dannysmc95** [comment]
@Lyokolux the developer does not seem active anymore, I was able to avoid the above issue by simply copying the main file into my code base and using it directly (works fine).

**Comment by bazingaedward** [comment]
@dannysmc95 could you give demo base on stackblitz？

**Comment by bazingaedward** [comment]
I'm sorry, I couldn't reproduce the corresponding error. Please check the relevant TypeScript configuration.

**Comment by dannysmc95** [comment]
> @dannysmc95 could you give demo base on stackblitz？

Sorry for such a delayed response, we stopped using the package when we hit the issue, and just used Monaco directly, apologies.

**Comment by Lyokolux** [comment]
> @bazingaedward
> 
> > @dannysmc95 could you give demo base on stackblitz？
> 
> Sorry for such a delayed response, we stopped using the package when we hit the issue, and just used Monaco directly, apologies.

So basically, we do the same and created our own MonacoEditor component
