### ISSUE TITLE
调用多次使用v-show或者v-if问题

### ISSUE THREAD

**Issue by MC-YCY** [bazingaedward/monaco-editor-vue3#14]
第一次打开弹窗没有问题
![image](https://user-images.githubusercontent.com/87837356/201068172-c760b238-e937-4543-9209-692417db1dfe.png)
使用v-if或者v-show切换语言就这个样子
![image](https://user-images.githubusercontent.com/87837356/201068098-461082c1-a609-44cf-9064-51360e521080.png)

**Comment by MC-YCY** [comment]
代码就是这个样子的
` <a-form-item v-if="
    nodeTypes.type == 'SHELL'
" :label="'脚本'" name="rawScript">
    <monaco-editor id="shell" theme="vs-dark" :language="nodeTypes.type.toLowerCase()" :width="'100%'"
        :height="420" v-model:value="formState.rawScript"></monaco-editor>
</a-form-item>

<a-form-item v-if="
    nodeTypes.type == 'PYTHON'
" :label="'脚本'" name="rawScript">
    <monaco-editor id="python" theme="vs-dark" :language="nodeTypes.type.toLowerCase()" :width="'100%'"
        :height="420" v-model:value="formState.rawScript"></monaco-editor>
</a-form-item>

<a-form-item v-if="nodeTypes.type == 'SQL'" :label="'SQL语句'" name="sql">
    <monaco-editor id="sql" theme="vs-dark" :language="nodeTypes.type.toLowerCase()" :width="'100%'"
        :height="420" v-model:value="formState.sql"></monaco-editor>
</a-form-item>`

**Comment by MC-YCY** [comment]
具体的代码就是这个样子的,
` <a-form-item v-if="
                    nodeTypes.type == 'SHELL'
                " :label="'脚本'" name="rawScript">
                    <monaco-editor id="shell" theme="vs-dark" :language="nodeTypes.type.toLowerCase()" :width="'100%'"
                        :height="420" v-model:value="formState.rawScript"></monaco-editor>
                </a-form-item>

                <a-form-item v-if="
                    nodeTypes.type == 'PYTHON'
                " :label="'脚本'" name="rawScript">
                    <monaco-editor id="python" theme="vs-dark" :language="nodeTypes.type.toLowerCase()" :width="'100%'"
                        :height="420" v-model:value="formState.rawScript"></monaco-editor>
                </a-form-item>

                <a-form-item v-if="nodeTypes.type == 'SQL'" :label="'SQL语句'" name="sql">
                    <monaco-editor id="sql" theme="vs-dark" :language="nodeTypes.type.toLowerCase()" :width="'100%'"
                        :height="420" v-model:value="formState.sql"></monaco-editor>
                </a-form-item>`

在 initMonaco()方法用this.$nextTick包裹方法代码无问题😐

**Comment by bazingaedward** [comment]
@MC-YCY 晚些时候测试复现下再回复你

**Comment by bazingaedward** [comment]
> 具体的代码就是这个样子的, `
> 
> ```
>             <a-form-item v-if="
>                 nodeTypes.type == 'PYTHON'
>             " :label="'脚本'" name="rawScript">
>                 <monaco-editor id="python" theme="vs-dark" :language="nodeTypes.type.toLowerCase()" :width="'100%'"
>                     :height="420" v-model:value="formState.rawScript"></monaco-editor>
>             </a-form-item>
> 
>             <a-form-item v-if="nodeTypes.type == 'SQL'" :label="'SQL语句'" name="sql">
>                 <monaco-editor id="sql" theme="vs-dark" :language="nodeTypes.type.toLowerCase()" :width="'100%'"
>                     :height="420" v-model:value="formState.sql"></monaco-editor>
>             </a-form-item>`
> ```
> 
> 在 initMonaco()方法用this.$nextTick包裹方法代码无问题😐

经测试，v-if不存在这个问题，v-show在切换到新的monitor-editor后显示空白，估计是未触发初始化，可以用this.$nextTick手动解决下，后续更新版本后会添加该测试用例。
