### ISSUE TITLE
在Vue3+Vite+TS项目中使用报错 Component is missing template or render function.

### ISSUE THREAD

**Issue by notfound945** [bazingaedward/monaco-editor-vue3#20]
# 问题

我根据 [See Stackblitz Demo](https://stackblitz.com/edit/vitejs-vite-bfx1bj) 中的DEMO在我的项目上使用了 monaco-editor-vue3，但遇到了控制台报错 **Component is missing template or render function.**，同时在页面上也未展示出monaco编辑器组件
<img width="689" alt="image" src="https://github.com/bazingaedward/monaco-editor-vue3/assets/29035326/afe8c381-e800-4165-86bf-cb3da46f60d0">

我也尝试在 Stackblitz 在线演示中检查，发现存在同样的问题
<img width="847" alt="image" src="https://github.com/bazingaedward/monaco-editor-vue3/assets/29035326/f8caf3ce-d02d-42e6-a009-c101f5d2e915">

# 环境
+ Windows 11
+ Vite `^4.3.9`
+ Vue `^3.3.4`
+ TypeScript `^5.0.2`

#  期望
期待得到您的支持与解决 👍

**Comment by bazingaedward** [comment]
好的，"^0.1.8"是这个版本引起的，在最新的0.1.9中已经修复
