### ISSUE TITLE
Is this package deprecated?

### ISSUE THREAD

**Issue by starnayuta** [bazingaedward/monaco-editor-vue3#21]
Is this package deprecated?

The following message is displayed on the [npm page](https://www.npmjs.com/package/monaco-editor-vue3).

``` txt
This package has been deprecated
Author message:

0.1.8
```
![image](https://github.com/bazingaedward/monaco-editor-vue3/assets/58112571/563117ae-9458-4364-bac6-4c1d9cfe0fa7)

**Comment by bazingaedward** [comment]
noop，The deprecated version is a temporary release, and a new version will be reissued later this week.
