### ISSUE TITLE
Readme links are broken

### ISSUE THREAD

**Issue by coofercat** [bazingaedward/monaco-editor-vue3#26]
In the README, the links in the 'options' prop section are broken:
```
Props
width: Editor width, eg: 800px or 800.
height: Editor height, eg: 800px or 800.
options: The [second argument] of [monaco.editor.create]
```
This looks like a good list of the options available: https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IStandaloneEditorConstructionOptions.html

**Comment by bazingaedward** [comment]
@coofercat  The links to some old versions of documents have been updated. We will synchronize the latest content shortly.

**Comment by bazingaedward** [comment]
> In the README, the links in the 'options' prop section are broken:
> 
> ```
> Props
> width: Editor width, eg: 800px or 800.
> height: Editor height, eg: 800px or 800.
> options: The [second argument] of [monaco.editor.create]
> ```
> 
> This looks like a good list of the options available: https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IStandaloneEditorConstructionOptions.html

@LiarOnce Thank you for your suggestion, the relevant links have been updated.
