### ISSUE TITLE
monaco-editor-vue3 直接引入 控制台报错

### ISSUE THREAD

**Issue by Xiangzi529** [bazingaedward/monaco-editor-vue3#28]
![image](https://github.com/bazingaedward/monaco-editor-vue3/assets/165776161/77b24288-df7a-4d0f-926c-331265829e1e)
![image](https://github.com/bazingaedward/monaco-editor-vue3/assets/165776161/2497af2d-44b5-4ddd-a314-44eb1fa511fa)

**Comment by bazingaedward** [comment]
@Xiangzi529 方便提供codepen或是stackblize的复现链接么

**Comment by Xiangzi529** [comment]
引入vite-plugin-monaco-editor解决了

**Comment by nanfb** [comment]
> 已解决vite-plugin-monaco-editor

vite5调用方式(monacoEditorPlugin as any).default({
			languageWorkers: [],
		}),

**Comment by Xiangzi529** [comment]
> > 已解决vite-plugin-monaco-editor
> 
> vite5调用方式(monacoEditorPlugin as any).default({ languageWorkers: [], }),

确实
