### ISSUE TITLE
封装成组件了 我如何来创建装饰器或者代码透镜呢 

### ISSUE THREAD

**Issue by Xiangzi529** [bazingaedward/monaco-editor-vue3#29]
封装成组件了 我如何来创建装饰器呢
我没办法拿到monaco这个类了好像
![image](https://github.com/bazingaedward/monaco-editor-vue3/assets/165776161/7cb1e226-1670-4982-9df2-0767ca59e1a9)

**Comment by bazingaedward** [comment]
在生命周期didMount时候可以拿到monaco，装饰器和code lens不清楚你的具体需求 @Xiangzi529

**Comment by bazingaedward** [comment]
![image](https://github.com/bazingaedward/monaco-editor-vue3/assets/6486768/92c574a3-9ece-4127-98ed-008b69b5c343)

**Comment by Xiangzi529** [comment]
> ![image](https://private-user-images.githubusercontent.com/6486768/335472394-92c574a3-9ece-4127-98ed-008b69b5c343.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzg0NjAsIm5iZiI6MTcxNzEzODE2MCwicGF0aCI6Ii82NDg2NzY4LzMzNTQ3MjM5NC05MmM1NzRhMy05ZWNlLTQxMjctOThlZC0wMDhiNjliNWMzNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMDY0OTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ4NDVlYmE3NmMwNGJhYzg2YmMxMDkxODI5ZDk4OWQ1ZWRlY2E0MDc2ZTdjZTQwZTVjMGM3NmUxY2E0YWNmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vFp_ki0Fyi3x587XlI2m2Cz9kk95-TQff5sErlNBAUY)

嗯嗯 我后来看到有这个事件 但是ts类型方面会有些问题 然后 我就用原生的写了 谢谢大佬回答
