### ISSUE TITLE
How to configure it with Vite

### ISSUE THREAD

**Issue by SagarVishal** [bazingaedward/monaco-editor-vue3#6]
I was able to integrate and bring the UI part but wasn't able to understand the webpack or the rollup part.
Can anyone help,  how do I use this with vite. Steps would be nice please or a demo would be great.

**Comment by bazingaedward** [comment]
@SagarVishal hi, here are some advices:
1. Vite is based on rollup, so the `rollup part` in readme will also be useful for vite
2. In this project source code, we also show the code with Vite already (local env: yarn dev), so you can check the vite.config.ts

And we know a live demo will be helpful, so will attach some demo( Stackblitz ) in recent days, if we finished, i will append to this issue

**Comment by bazingaedward** [comment]
Take a look: https://stackblitz.com/edit/vitejs-vite-bfx1bj?file=src/App.vue

**Comment by bazingaedward** [comment]
[StackBlitz](https://stackblitz.com/edit/vitejs-vite-bfx1bj?file=src/App.vue)
